# Platforms:
#   - aarch64-apple-darwin
#   - aarch64-linux-gnu
#   - aarch64-linux-musl
#   - armv6l-linux-gnueabihf
#   - armv6l-linux-musleabihf
#   - armv7l-linux-gnueabihf
#   - armv7l-linux-musleabihf
#   - i686-linux-gnu
#   - i686-linux-musl
#   - i686-w64-mingw32
#   - powerpc64le-linux-gnu
#   - x86_64-apple-darwin
#   - x86_64-linux-gnu
#   - x86_64-linux-musl
#   - x86_64-unknown-freebsd
#   - aarch64-unknown-freebsd
#   - x86_64-w64-mingw32
#
# Targets:
#   - platform-libgfortran3
#   - platform-libgfortran4
#   - platform-libgfortran5
#
# Note: We can determine our target with `Base.BinaryPlatforms.host_triplet()`.
#
# Additional options supported by this build_tarballs.jl:
# --metis4: Compile libHSL with METIS 4 instead of METIS 5.
# --openblas: Compile libHSL with OpenBLAS32 instead of libblastrampoline.
# --examples: Compile the C and Fortran examples of libHSL.
# --static: Generate a static library libhsl.a in addition to the shared one.
# --modules: Export the module files (*.mod) generated by the Fortran compiler.
# --debugging: Compile libHSL in debug mode.
# --deps: Export the dependencies of libHSL.
#
# Examples:
# julia --color=yes build_tarballs.jl x86_64-linux-gnu-libgfortran5 --verbose --deploy="local"
# julia --color=yes build_tarballs.jl x86_64-w64-mingw32-libgfortran5 --verbose --deploy="local"
# julia --color=yes build_tarballs.jl x86_64-apple-darwin-libgfortran4,x86_64-apple-darwin-libgfortran5 --verbose --deploy="local"
# julia --color=yes build_tarballs.jl aarch64-apple-darwin-libgfortran5 --verbose --deploy="local"
# julia --color=yes build_tarballs.jl x86_64-unknown-freebsd-libgfortran5 --openblas --debugging --metis4 --examples --verbose --deploy="local"
#
# The package HSL_jll.jl is generated in `~/.julia/dev/`.

function remove!(v, item)
  deleteat!(v, findall(x -> x == item, v))
end

using BinaryBuilder, Pkg

name = "HSL"
version = v"2024.11.28"

## METIS4 -- METIS5
if "--metis4" ∈ ARGS
  libmetis_version = "4"
  libmetis_name = "metis4"
  libmetis_jll = Dependency(PackageSpec(name="METIS4_jll", uuid ="40b5814e-7855-5c9f-99f7-a735ce3fdf8b"))
  remove!(ARGS, "--metis4")
else
  libmetis_version = "5"
  libmetis_name = "metis"
  libmetis_jll = Dependency(PackageSpec(name="METIS_jll", uuid="d00139f3-1899-568f-a2f0-47f597d42d70"))
end

##  OpenBLAS32 -- LBT
if "--openblas" ∈ ARGS
  julia_compat = "1.6"
  libblas_liblapack_name = "openblas"
  libblas_liblapack_jll = Dependency(PackageSpec(name="OpenBLAS32_jll", uuid="656ef2d0-ae68-5445-9ca0-591084a874a2"))
  remove!(ARGS, "--openblas")
else
  julia_compat = "1.9"
  libblas_liblapack_name = "blastrampoline"
  libblas_liblapack_jll = Dependency(PackageSpec(name="libblastrampoline_jll", uuid="8e850b90-86db-534c-a0d3-1478176c7d93"), compat="5.4.0")
end

# C and Fortran examples
if "--examples" ∈ ARGS
  examples = true
  remove!(ARGS, "--examples")
else
  examples = false
end

# Static library libhsl.a
if "--static" ∈ ARGS
  library_type = "both"
  remove!(ARGS, "--static")
else
  library_type = "shared"
end

# Fortran modules
if "--modules" ∈ ARGS
  modules = true
  remove!(ARGS, "--modules")
else
  modules = false
end

# Compilation in debug or release mode
if "--debugging" ∈ ARGS
  mode = "debug"
  remove!(ARGS, "--debugging")
else
  mode = "release"
end

# Export the dependencies of libHSL
if "--deps" ∈ ARGS
  deps = true
  remove!(ARGS, "--deps")
else
  deps = false
end

# Collection of sources required to complete build
sources = [ 
  DirectorySource("./libHSL.v$version")
]

# Bash recipe for building across all platforms
script = ""

if deps
  script *= raw"""
# Export dependencies
mkdir ${prefix}/deps
cd ${libdir}
for file in $(ls .); do
   if [[ -f $file ]]; then
      if [[ -z $(ls -la $file | grep 'artifacts') ]]; then
         cp -P ${file} ${prefix}/deps/${file}
      else
         cp -L ${file} ${prefix}/deps/${file}
      fi
   fi
done
cd ${prefix}
cp -rL share/licenses deps/licenses
chmod -R u=rwx deps
tar -czvf deps.tar.gz deps
rm -r deps
"""
end

script *= raw"""
cd $WORKSPACE/srcdir

if [[ "${target}" == *mingw* ]]; then
  MPI="msmpi"
  LBT="blastrampoline-5"
else
  MPI="mpifort"
  LBT="blastrampoline"
fi

meson setup builddir --cross-file=${MESON_TARGET_TOOLCHAIN} \
                     --prefix=$prefix \
                     -Dlibmpi=$MPI \
"""

if libblas_liblapack_name == "blastrampoline"
    script *= raw"""
                     -Dlibblas=$LBT \
                     -Dliblapack=$LBT \
"""
else
    script *= """
                     -Dlibblas=$(libblas_liblapack_name) \\
                     -Dliblapack=$(libblas_liblapack_name) \\
"""
end

script *= """
                     --buildtype=$(mode) \\
                     --default-library=$(library_type) \\
                     -Dexamples=$(examples) \\
                     -Dlibmetis=$(libmetis_name) \\
                     -Dlibmetis_version=$(libmetis_version) \\
                     -Dmodules=$(modules)

meson compile -C builddir
meson install -C builddir
"""

# These are the platforms we will build for by default, unless further
# platforms are passed in on the command line
platforms = supported_platforms()
platforms = expand_gfortran_versions(platforms)

products = [
  LibraryProduct("libhsl", :libhsl),
]

# Dependencies that must be installed before this package can be built
dependencies = [
  Dependency(PackageSpec(name="CompilerSupportLibraries_jll", uuid="e66e0078-7015-5450-92f7-15fbd957f2ae")),
  Dependency(PackageSpec(name="MPICH_jll", uuid="7cb0a576-ebde-5e09-9194-50597f1243b4"); platforms=filter(!Sys.iswindows, platforms)),
  Dependency(PackageSpec(name="MicrosoftMPI_jll", uuid="9237b28f-5490-5468-be7b-bb81f5f5e6cf"); platforms=filter(Sys.iswindows, platforms)),
]
push!(dependencies, libmetis_jll, libblas_liblapack_jll)

@info "libHSL is compiled with the following dependencies:"
for dep in dependencies
  @info "$(dep.pkg.name)"
end

for (i, arg) in enumerate(ARGS)
  if occursin("--deploy", arg) && (arg != "--deploy=local")
    @warn "libHSL and HSL_jll.jl can't be distributed. The option $arg has been replaced by --deploy=local."
    ARGS[i] = "--deploy=local"
  end
end

# Build the tarballs, and possibly a `build.jl` as well.
build_tarballs(ARGS, name, version, sources, script, platforms, products, dependencies; julia_compat=julia_compat, preferred_gcc_version=v"5")
